services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False" 
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
      - "./servers.json:/pgadmin4/servers.json"
      # This file auto-fills the password for the 'pgdatabase' host
      - "./pgpass:/tmp/pgpassfile"
    ports:
      - "8085:80"

  pipeline:
    build:
      context: ./pipeline           
      dockerfile: Dockerfile
    image: pipeline:v001 
    command:
      - --pg_user=root
      - --pg_pass=root
      - --pg_host=pgdatabase
      - --pg_port=5432
      - --pg_db=ny_taxi
      - --pg_table=yellow_taxi
    depends_on:
      - pgdatabase

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:



